### ISSUE TITLE
Not work for NVIDIA 460.32.03 driver

### ISSUE THREAD

**Issue by liuliu** [DualCoder/vgpu_unlock#10]
On Ubuntu 20.04 with 5.8.0.48 kernel.

Try to install 460.32.03 driver downloaded in the portal (`NVIDIA-Linux-x86_64-460.32.03-grid.run`)

Minor issue, have to fix `nvidia/nv-vgpu-vmbus.c` to rename `PAGE_KERNEL_RX` to `PAGE_KERNEL_ROX` to make dkms happy.

 1. Cannot find fore-mentioned `vgpud.service` and `vgpu-mgr.service`, only `gridd.service` available.
 2. Upon switching to vgpu_unlock to launch gridd.service, still get license issue:

```
# systemctl status nvidia-gridd.service

Apr 10 00:41:28 sz77 systemd[1]: Starting NVIDIA Grid Daemon...
Apr 10 00:41:28 sz77 systemd[1]: Started NVIDIA Grid Daemon.
Apr 10 00:41:29 sz77 nvidia-gridd[1685]: Started (1685)
Apr 10 00:41:32 sz77 nvidia-gridd[1685]: Licensing not supported for GPUs in the system
Apr 10 00:41:32 sz77 nvidia-gridd[1685]: Failed to handle license change events
Apr 10 00:41:32 sz77 nvidia-gridd[1685]: Licensing not supported for GPUs in the system
Apr 10 00:41:32 sz77 nvidia-gridd[1685]: Failed to unlock PID file: Bad file descriptor
Apr 10 00:41:32 sz77 nvidia-gridd[1685]: Failed to close PID file: Bad file descriptor
Apr 10 00:41:32 sz77 nvidia-gridd[1685]: Shutdown (1685)
Apr 10 00:41:32 sz77 systemd[1]: nvidia-gridd.service: Succeeded.
```

**Comment by liuliu** [comment]
I probably should use the `NVIDIA-Linux-x86_64-460.32.04-vgpu-kvm.run` file. Trying.

**Comment by liuliu** [comment]
That is indeed the issue. I can now see `nvidia_vgpu_vfio`. Closing. Sorry about the noise.

**Comment by intdel** [comment]
I was  wondering where you got NVIDIA-Linux-x86_64-460.32.04-vgpu-kvm.run from?

**Comment by AlexHaber** [comment]
> I was wondering where you got NVIDIA-Linux-x86_64-460.32.04-vgpu-kvm.run from?
I found it on an open directory by searching the file name with google. It will be in an archive called `NVIDIA-GRID-Linux-KVM-460.32.04-460.32.03-461.33.zip`, although searching the filename of the zip doesn't return any meaningful results. 

Since I don't have the original, I can't be 100% certain that it hasn't been tampered with, but the SHA256 of `NVIDIA-Linux-x86_64-460.32.03-grid.run` file in the archive matches the one hosted by google, so I am inclined to trust it.

**Comment by liuliu** [comment]
If it helps:

```
$ sha256sum NVIDIA-GRID-Linux-KVM-460.32.04-460.32.03-461.33.zip 
b92760e3721d88575db982dfd396584c966747887d20b8d8df82b38638480849  NVIDIA-GRID-Linux-KVM-460.32.04-460.32.03-461.33.zip
$ sha256sum NVIDIA-Linux-x86_64-460.32.04-vgpu-kvm.run 
f47f6006891df59ede8d2484376d4b97f2f80dfb5ca909aed1743532880b5e01  NVIDIA-Linux-x86_64-460.32.04-vgpu-kvm.run
```

**Comment by kwibjo** [comment]
I can install 460.32.03-grid without issue (using the same archive you found) however, I'm missing `/lib/systemd/system/nvidia-vgpud.service` and `/lib/systemd/system/nvidia-vgpu-mgr.service` replacing it with 460.32.04-vgpu-kvm breaks my desktop and pins my GPU at 100% utilisation. Any suggestions? I'm also on ubuntu 20.04.2 kernel 5.8.0-48-generic

(I set power level to 100W manually to prevent a house fire 😂)
```
Sun Apr 11 08:31:25 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.04    Driver Version: 460.32.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    On   | 00000000:0A:00.0 Off |                  N/A |
| 30%   43C    P0   112W / 100W |      0MiB / 24230MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by liuliu** [comment]
`-vgpu-kvm` driver not meant to run desktop, it supposes to be the driver on your host system (think of Proxmox or similiar). I merged the two drivers together this morning so I can run my desktop properly while having `vgpu_vfio` module, but it has problems with CUDA (it cannot successfully run CUDA programs on the host system). I didn't dig further after that.

**Comment by kwibjo** [comment]
Yeah right I forgot these are for datacenter-esque devices 😅 

I'm not sure what's causing the 100% utilisation still but I suppose I'll give merging drivers a go. Thanks

**Comment by liuliu** [comment]
Yeah. Once you `./xxx.run -x` extract the driver out, it is pretty simple to merge. I even modified the `vgpud.service` and `os-interface.c` file etc so I don't have to manually adjust every time for `vgpu_unlock`. Need to modify the version strings within `kernel/nvidia.o_binary` and some other vgpu related binary blobs otherwise they will yell version mismatch (the host driver is 460.32.04 while the guest driver is 460.32.03 (this is actually I believe the generic driver)).

**Comment by liuliu** [comment]
@kwibjo as I browse through the documentation (you should as well!), this may be relevant to you:
![Screenshot from 2021-04-10 16-35-39](https://user-images.githubusercontent.com/127987/114287368-1c07cd80-9a1b-11eb-8b3c-f5133d55a81b.png)

**Comment by kwibjo** [comment]
Thanks for your help but I'm still trying to get vgpu_unlock to work 😅 I not sure but I think I should make a new issue for this.

I haven't tried installing the merged drivers yet since I want to get the script working first. My card is still reporting as a 3090 not as a RTX A40 and I don't have the `/sys/class/mdev_bus` directory. 😔

I've modified the systemd services and rebuilt the kernel modules, the only thing I'm not 100% on is where the line `ldflags-y += -T <path_to_vgpu_unlock>/kern.ld` is meant to go. I modified it to point to the correct directory and placed it right below the #include

I also had to hard link the services to /etc from /lib otherwise they weren't even recognised even after reloading daemons but they're not exiting with errors so I don't know
```
● nvidia-vgpud.service - NVIDIA vGPU Daemon
     Loaded: loaded (/etc/systemd/system/nvidia-vgpud.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Sun 2021-04-11 09:33:05 ACST; 3min 53s ago
    Process: 944 ExecStart=/lib/vgpu_unlock/vgpu_unlock /usr/bin/nvidia-vgpud (code=exited, status=0/SUCCESS)
    Process: 1165 ExecStopPost=/bin/rm -rf /var/run/nvidia-vgpud (code=exited, status=0/SUCCESS)
   Main PID: 1057 (code=exited, status=0/SUCCESS)

Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpud[1102]: BAR1 Length: 0x800
Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpud[1102]: Frame Rate Limiter enabled: 0x1
Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpud[1102]: Number of Displays: 1
Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpud[1102]: Max pixels: 8847360
Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpud[1102]: Display: width 4096, height 2160
Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpud[1102]: License: NVIDIA-vComputeServer,9.0;Quadro-Virtual-DWS,5.0
Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpud[1102]: PID file unlocked.
Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpud[1102]: PID file closed.
Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpud[1102]: Shutdown (1102)
Apr 11 09:33:05 jai-X570-AORUS-MASTER systemd[1]: nvidia-vgpud.service: Succeeded.
```
```
# systemctl status nvidia-vgpu-mgr.service
● nvidia-vgpu-mgr.service - NVIDIA vGPU Manager Daemon
     Loaded: loaded (/etc/systemd/system/nvidia-vgpu-mgr.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-04-11 09:33:04 ACST; 2min 55s ago
    Process: 942 ExecStart=/lib/vgpu_unlock/vgpu_unlock /usr/bin/nvidia-vgpu-mgr (code=exited, status=0/SUCCESS)
   Main PID: 1049 (vgpu_unlock)
      Tasks: 11 (limit: 38356)
     Memory: 85.4M
     CGroup: /system.slice/nvidia-vgpu-mgr.service
             ├─1049 /bin/python3 /lib/vgpu_unlock/vgpu_unlock -f /usr/bin/nvidia-vgpu-mgr
             └─1113 /usr/bin/nvidia-vgpu-mgr

Apr 11 09:33:03 jai-X570-AORUS-MASTER systemd[1]: Starting NVIDIA vGPU Manager Daemon...
Apr 11 09:33:04 jai-X570-AORUS-MASTER systemd[1]: Started NVIDIA vGPU Manager Daemon.
Apr 11 09:33:05 jai-X570-AORUS-MASTER nvidia-vgpu-mgr[1113]: notice: vmiop_env_log: nvidia-vgpu-mgr daemon started
```

**Comment by AlexHaber** [comment]
I still haven't managed to get it working either, however one thing of note is that kernels >5.10 remove set_fs(), which breaks the dkms of the unmodified driver. This also broke the standard NVIDIA driver at one point and there is a patch to fix it somewhere (but now that I am looking for it I can't find it again).

**Comment by Rotho98** [comment]
@liuliu could you send me the edited driver or explain how I could sort it myself

**Comment by AlexHaber** [comment]
Ok so I have done some digging around and here is what I understand so far. 

NVIDIA-Linux-x86_64-460.32.04-vgpu-kvm.run is the driver for the "host" and is intended for headless servers. 
NVIDIA-Linux-x86_64-460.32.03-grid.run is the driver intended for the "guest" VMs

I also compared the NVIDIA-Linux-x86_64-460.32.03-grid driver to NVIDIA-Linux-x86_64-460.32.03 (consumer) the main differences are the added nvidia-gridd and libFlxCore64 (FlexNet Embedded) files, and most of the other changes are to accommodate those added files.  

```Only in NVIDIA-Linux-x86_64-460.32.03-grid: libFlxComm64.so.2018.02
Only in NVIDIA-Linux-x86_64-460.32.03-grid: libFlxCore64.so.2018.02
Only in NVIDIA-Linux-x86_64-460.32.03-grid: nvidia-gridd
Only in NVIDIA-Linux-x86_64-460.32.03-grid: nvidia-gridd.1.gz```

What we are trying to achieve is to merge the kvm files into a client driver, so we can still use the GPU on the host machine. I think the normal consumer driver would be best for this, as the grid version is intended for use with vGPUs and has licensing stuff.  Once we have a merged driver we can patch it using the vgpu_unlock method, so we can use the vGPU function on normal consumer GPUs. 

Our goal, however, seems outside the scope of the vgpu_unlock project, which only unlocks the typical grid driver for their intended use case.

**Comment by cdknight** [comment]
I just saw this and it was something I thought of too—good to know it is being worked on. 

I wonder if the converse of this project is possible, where you can spoof the model of the GRID GPU in the virtual machine so you don't have to use the GRID drivers (which are a huge pain—you need to set up a licensing server, it doesn't get updated, etc.) on a guest?

**Comment by liuliu** [comment]
> What we are trying to achieve is to merge the kvm files into a client driver, so we can still use the GPU on the host machine. I think the normal consumer driver would be best for this, as the grid version is intended for use with vGPUs and has licensing stuff. Once we have a merged driver we can patch it using the vgpu_unlock method, so we can use the vGPU function on normal consumer GPUs.
> 
> Our goal, however, seems outside the scope of the vgpu_unlock project, which only unlocks the typical grid driver for use with consumer GPUs in the intended use case. I also don't yet know if guest vGPU licensing is going to be an issue.

Correct. So far, I was able to merge the consumer driver with the vgpu-kvm driver and install it.

Good side:

 1. Display uses NVIDIA driver hence you are at the right resolution now;
 2. I haven't tried any testing program with OpenGL, but Steam and Civ6 opens with this setup;
 3. nvidia_vgpu_vfio shows up as kernel module.

Bad side:

 1. CUDA doesn't work at all, fail at initialization;
 2. Because of 1, I am not inclined to setup a vgpu and try it in a VM at the moment.

**Comment by kwibjo** [comment]
I was able to get `/sys/class/mdev_bus` to populate after pulling #cce7b5d however it's still recognised as a 3090 and looking for vGPU types with `# grep -i "vgpu-type" nvidia-*/name` returns nothing. Baby steps though I suppose 😁

**Comment by javyxu** [comment]
> If it helps:
> 
> ```
> $ sha256sum NVIDIA-GRID-Linux-KVM-460.32.04-460.32.03-461.33.zip 
> b92760e3721d88575db982dfd396584c966747887d20b8d8df82b38638480849  NVIDIA-GRID-Linux-KVM-460.32.04-460.32.03-461.33.zip
> $ sha256sum NVIDIA-Linux-x86_64-460.32.04-vgpu-kvm.run 
> f47f6006891df59ede8d2484376d4b97f2f80dfb5ca909aed1743532880b5e01  NVIDIA-Linux-x86_64-460.32.04-vgpu-kvm.run
> ```

hello,Could you please provide the download addresses of these two files？Thank you very much！

**Comment by PeterHindes** [comment]
> > What we are trying to achieve is to merge the kvm files into a client driver, so we can still use the GPU on the host machine. I think the normal consumer driver would be best for this, as the grid version is intended for use with vGPUs and has licensing stuff. Once we have a merged driver we can patch it using the vgpu_unlock method, so we can use the vGPU function on normal consumer GPUs.
> > Our goal, however, seems outside the scope of the vgpu_unlock project, which only unlocks the typical grid driver for use with consumer GPUs in the intended use case. I also don't yet know if guest vGPU licensing is going to be an issue.
> 
> Correct. So far, I was able to merge the consumer driver with the vgpu-kvm driver and install it.
> 
> Good side:
> 
> 1. Display uses NVIDIA driver hence you are at the right resolution now;
> 2. I haven't tried any testing program with OpenGL, but Steam and Civ6 opens with this setup;
> 3. nvidia_vgpu_vfio shows up as kernel module.
> 
> Bad side:
> 
> 1. CUDA doesn't work at all, fail at initialization;
> 2. Because of 1, I am not inclined to setup a vgpu and try it in a VM at the moment.

Hey would you mind providing the driver you created? I'm interested in creating a patch file.

**Comment by TheAifam5** [comment]
Hey, what is that "licensing stuff"?
