### ISSUE TITLE
vGPU Working but I get error 43

### ISSUE THREAD

**Issue by mircea-pavel-anton** [DualCoder/vgpu_unlock#102]
So i tried both following Jeff's tutorial (CraftComputing) on PVE 7.1 as well as [this one](https://gitlab.com/polloloco/vgpu-proxmox) on PVE 7.2 and on both instances I managed to configure the vGPU to be enabled and I can assign a vGPU to a Windows 11 VM. Problem is, I get error code 43 inside the VM every time. I tried the "traditional" ways to address that, i.e. setting the cpu flags `hidden=1,flags=+pcid`, i have set the `display=none`, but to no avail.

I have 2 GPUs in the system, an RTX 2070S and a GTX 1050. vGPU seems to be working for both as in `mdevctl types` lists options for both GPUs. Any ideas?

**Comment by shiwaimanong** [comment]
I tested GTX 1050, GTX 1050 Ti, GTX 1660, RTX 2060, they works fine with windows 11.

* VM Host System: Ubuntu 22.04 Desktop
* VM Host Driver: NVIDIA-Linux-x86_64-510.85.03-vgpu-kvm.run
* vgpu patcher: https://github.com/VGPU-Community-Drivers/vGPU-Unlock-patcher
* vgpu unlock: https://github.com/mbilker/vgpu_unlock-rs.git

`/etc/vgpu_unlock/profile_override.toml` :

```
[profile.nvidia-257]
num_displays = 1
display_width = 1920
display_height = 1080
max_pixels = 2073600
```

Windows 10/11 Gust GPU Driver: 496.49-quadro-rtx-desktop-notebook-win10-win11-64bit-international-dch-whql.exe

Notice: RTX 3060 or newer not support!

**Comment by angst911** [comment]
Make sure secure boot is disabled in the UEFI BIOS
