### ISSUE TITLE
Will this work on enterprise grade GPU like NVIDIA Tesla M10 but to eliminate the need of NVIDIA licensing?

### ISSUE THREAD

**Issue by justinktn** [DualCoder/vgpu_unlock#107]
I know that this will work on consumer-grade GPU on most Pascal and Turing-based GPUs but will this work for an enterprise-grade GPU specialized for vGPU but to remove the requirements of activating it through a license server? Thanks

**Comment by efschu** [comment]
If you want to give the mdev to a Windows VM, then you could just spoof the PCIe IDs in your VM config, to match the IDs of a Quadro. Then install Quadro Driver in Windows.

Otherwise you could do the "each day grid driver license reset"
