### ISSUE TITLE
Maxwell 2.0 support? + where is driver?

### ISSUE THREAD

**Issue by Casul51** [DualCoder/vgpu_unlock#11]
Basically Tesla M60 have GM204 (as GTX970), so virtually you can just add both product IDs and it should work. 
(I would test myself but I cant find a driver)

By the way, I feel like an idiot, but I can't find a GRID vGPU driver, on [Nvidia download page](https://www.nvidia.com/download/index.aspx?lang=en-us), when I select GRID > vGPU, there is no Linux in operating system, there is xenServer and vSphere, inside windows drivers + NVIDIA-vGPU-kepler-xenserver-version.rpm 
So, should I use Tesla driver or where can I find a proper driver?

**Comment by arki05** [comment]
The Drivers aren't publicly available, see https://www.nvidia.com/en-us/drivers/vgpu-software-driver/ 
You can register for a free 90-day evaluation.

**Comment by cdknight** [comment]
Going off this thread, is there a compatible GPU for the GTX 780? I don't think there are any and https://www.techpowerup.com/gpu-specs/nvidia-gk110.g136 says that there are only Tesla K20* models for the 780 (which don't have vGPU support), so I'm guessing it's a no.

**Comment by KrutavShah** [comment]
GK110 not supported by vGPU.

**Comment by cdknight** [comment]
@Casul51 looks like you can get them here too: https://cloud.google.com/compute/docs/gpus/install-grid-drivers#installing_grid_drivers

**Comment by KrutavShah** [comment]
Maxwell support coming to vgpu_unlock script, hang tight as we add a ton more PCI IDs. More updates will be posted in the discord as we workout Kepler support.

**Comment by cdknight** [comment]
Is there a link to this Discord server? I would like to keep track of the Kepler support

**Comment by KrutavShah** [comment]
[https://discord.gg/skvCTDAZnV](url)

Everyone is encouraged to join to keep up with updates and discuss the project. We are currently testing Maxwell, Kepler, and Volta support right now.

**Comment by DualCoder** [comment]
I am closing this since we expect supported Maxwell cards to work.
