### ISSUE TITLE
ESXi support?

### ISSUE THREAD

**Issue by leoleoasd** [DualCoder/vgpu_unlock#12]
Can this hack be used on vsphere/esxi? How can i set it up?

**Comment by hetzbh** [comment]
Nope. The drivers are different and you'll need to do a lot of modifications to make it run on ESXi, as much as I understood.

**Comment by leoleoasd** [comment]
> Nope. The drivers are different and you'll need to do a lot of modifications to make it run on ESXi, as much as I understood.

Welp, okay. 

Also, can this work on Proxmox VE? I've never used PVE before but it seems that it is just regular Linux.

**Comment by r33int** [comment]
> > Nope. The drivers are different and you'll need to do a lot of modifications to make it run on ESXi, as much as I understood.
> 
> 
> 
> Welp, okay. 
> 
> 
> 
> Also, can this work on Proxmox VE? I've never used PVE before but it seems that it is just regular Linux.

Yes, this works on Proxmox.
