### ISSUE TITLE
Few details please

### ISSUE THREAD

**Issue by hetzbh** [DualCoder/vgpu_unlock#13]
First, great project!

Second - could someone specify the vGPU driver version (and the clients versions) that is working with this hack? I'm pretty sure that within days, nVidia will release a new driver which will block this hack from working..

Another (a bit non related question) - If I recall correctly, you'll need to pay a monthly/yearly license to use the vGPU feature or is it something else? 

Thanks

**Comment by AlexHaber** [comment]
Issue #10 has some info about what drivers to use. 

This project only allows the "host" driver to be used on unsupported GPUs, the guest VMs still need the licenses as normal. There is a 90 day trial.

**Comment by cdknight** [comment]
I made a Gist detailing how to do it on Proxmox (steps should be similar for other distros if you know what you're doing): https://gist.github.com/cdknight/8f63a66d3280e6d5bf12dd4f4dac9183

The steps may be a bit lacking/nonfunctional (for example, with regard to how to view the output from the vGPU); I might update this later. It should, however, give you a general idea on how to do the whole thing.

**Comment by DualCoder** [comment]
> First, great project!
> 
> Second - could someone specify the vGPU driver version (and the clients versions) that is working with this hack? I'm pretty sure that within days, nVidia will release a new driver which will block this hack from working..

The "Linux with KVM" variant version 11 (450.102) and 12 (460.32.04) has been successfully tested with some Pascal and Turing based graphics cards. Other versions and cards may or may not work.

> Another (a bit non related question) - If I recall correctly, you'll need to pay a monthly/yearly license to use the vGPU feature or is it something else?

Yes, you are correct. A license is required for each concurrently running VM. Please consult the official vGPU licensing material for further information. vgpu\_unlock makes no changes to the licensing scheme.
