### ISSUE TITLE
Titan V support?

### ISSUE THREAD

**Issue by oscarbg** [DualCoder/vgpu_unlock#14]
Hi,
seems there is a Tesla V100 ,so Titan V support should be possible, right?
thanks..

**Comment by KrutavShah** [comment]
We are adding support for volta and maxwell and many new cards right now. Updates will be pushed soon. Lots of new PCI IDs, so hang tight!

**Comment by KrutavShah** [comment]
Added support, will be added to this repo after pull request is completed. Thank you. One more thing, what's your PCI ID?

**Comment by KrutavShah** [comment]
This issue can now be closed, volta support is in place.
