### ISSUE TITLE
Notebook variants of GPUs not supported?

### ISSUE THREAD

**Issue by Evengard** [DualCoder/vgpu_unlock#15]
Hello!

It seems that the notebook PCI IDs are not supported (specifically, I have a GTX 1060 6GB with Max-Q Design). Are they completely unable to work with vGPU, or they can be patched to work too? It seems that they have the ID of 1C20.

**Comment by KrutavShah** [comment]
They will be supported soon. So far Maxwell notebook cards have been added to the list in our community repo for this project, available on the discord server. We hope to get that on here as well, though we would need to contact DualCoder directly to add code to this project.

**Comment by Evengard** [comment]
Good!
Can you provide a link to this Discord server, or is it a private one?

**Comment by KrutavShah** [comment]
https://discord.gg/skvCTDAZnV

Everyone is encouraged to join to keep up with updates and discuss the project. We are currently testing Maxwell, Kepler, and Volta support right now.

**Comment by KrutavShah** [comment]
This issue can now be closed, mobile support is confirmed by some testers on the Discord.
