### ISSUE TITLE
Maxwell support

### ISSUE THREAD

**Issue by regulskimichal** [DualCoder/vgpu_unlock#16]
Is it possible to introduce GeForce 900-series to this project? GTX 970 seems to have the same chip GM204 as Tesla M6 which should support vGPU.

**Comment by KrutavShah** [comment]
https://discord.gg/skvCTDAZnV

Everyone is encouraged to join to keep up with updates and discuss the project. We are currently testing Maxwell, Kepler, and Volta support right now.

**Comment by KrutavShah** [comment]
It's coming :)

**Comment by KrutavShah** [comment]
Added support yesterday, give it a try!

**Comment by gremilkar** [comment]
I have GeForce 960 (GPU Code NameGM206-300), anybody does know will it work? Thanks.

**Comment by DualCoder** [comment]
> Is it possible to introduce GeForce 900-series to this project? GTX 970 seems to have the same chip GM204 as Tesla M6 which should support vGPU.

Maxwell cards has been added.

> I have GeForce 960 (GM206-300), anybody does know will it work? Thanks.

That is not in the list of added cards, it is unlikely to work.

I will close this issue since I expect supported cards to work, if that is not the case then this can be reopened.
