### ISSUE TITLE
Much more support for other cards?!

### ISSUE THREAD

**Issue by darkman1983** [DualCoder/vgpu_unlock#21]
Stumbled upon this https://envytools.readthedocs.io/en/latest/hw/pciid.html

There you can find many device ID's :-)
Might this be of any use? :,-)

**Comment by KrutavShah** [comment]
Yes, I am adding a ton more cards. Please join the discord server for more information and discussion. We have a channel called "gpu survey" where we get the names of cards, and that allows us to see what to add next.

**Comment by imtrobin** [comment]
what's the discord server?

**Comment by KrutavShah** [comment]
https://discord.gg/skvCTDAZnV

**Comment by DualCoder** [comment]
> Stumbled upon this https://envytools.readthedocs.io/en/latest/hw/pciid.html
> 
> There you can find many device ID's :-)
> Might this be of any use? :,-)

Yes, the envytools repository contains what is probably the best low-level documentation for NVIDIA GPUs that is publicly available.

Anyway, I will close this since we have added a lot of cards recently.
