### ISSUE TITLE
Does this still require a nvidia license server?

### ISSUE THREAD

**Issue by magauthority** [DualCoder/vgpu_unlock#22]
I'm looking to set this up on my proxmox server but have a couple of questions... 
Does this still require a license server? 
Will this work on Proxmox 6.3-6?
I've got two cards in my test server, a quandro p2000, and a GTX 1660 super..  is there some way to use only one for this project, or will both be affected should I build this solution? 
And I did sign up at nvidia for a trial license for 90 days, but there are a lot of different drivers, which one should I use for my hardware? 
Thanks for this work, this is very exciting stuff!!

**Comment by KrutavShah** [comment]
Yes, a license server and the appropriate licenses can be downloaded from the Nvidia licensing portal and installed on Linux or Windows.

We do have a public license server handing out licenses in our Discord server if you want to use that.

**Comment by magauthority** [comment]
That would be awesome. I tried the discord link posted in another thread, but it says it expired. Can you shoot me one? Please and thank you.

**Comment by KrutavShah** [comment]
https://discord.gg/qh6dvPtxvb

**Comment by DualCoder** [comment]
> I'm looking to set this up on my proxmox server but have a couple of questions...
> Does this still require a license server?

Yes.

> Will this work on Proxmox 6.3-6

Yes

> I've got two cards in my test server, a quandro p2000, and a GTX 1660 super.. is there some way to use only one for this project, or will both be affected should I build this solution?

One, and only one of the cards will be affected by vgpu\_unlock, unfortunately the current version of vgpu\_unlock does not have a way to select or report which one. Also simply installing the vGPU drivers will likely affect all cards.

> And I did sign up at nvidia for a trial license for 90 days, but there are a lot of different drivers, which one should I use for my hardware?

You would probably want the "Linux with KVM" variant, version 12.1 (460.32.04).

**Comment by KrutavShah** [comment]
This issue can now be closed safely.
