### ISSUE TITLE
Will be added the GTX 1050 Ti also?

### ISSUE THREAD

**Issue by valepe** [DualCoder/vgpu_unlock#24]

**Comment by KrutavShah** [comment]
It will be once the currently open pull request is accepted. Thanks for your patience!

**Comment by KrutavShah** [comment]
1050 Ti is now added, give it a try.

**Comment by zcemycl** [comment]
@KrutavShah I have a GTX 1050 Ti 4gb desktop. When I do `mdevctl types`, it does not list anything but my `vgpu unlock message` is showing. 
Is GTX 1050 Ti supported?

**Comment by DualCoder** [comment]
@zcemycl The 1050 Ti should be supported. I suggest you look at the logs for nvidia-vgpud `journalctl -u nvidia-vgpud` it should say "vgpu_unlock loaded." and it shouldn't contain any obvious errors.
