### ISSUE TITLE
Non-DKMS Method Possibility

### ISSUE THREAD

**Issue by moriel5** [DualCoder/vgpu_unlock#29]
As someone who does not use NVidia graphics currently, this is more of a "food for thought" question, however, would this be possible without relying on DKMS?

For example, on distros that do not employ DKMS, such as Solus.

**Comment by KrutavShah** [comment]
Nvidia certifies enterprise Linux such as RHEL for vGPU, and we also test on Debian, both of which use DKMS. There are many other distributions of Linux out there that may not work with this technology for one reason or another, or require a level of modifications to work. This unlock tool uses DKMS, so it’s best to use an OS that supports it, and one that is known working with vGPU.

**Comment by moriel5** [comment]
I understand that, and I was not asking for support, nor to change what is already existing.

My question was a theoretical question, in theory, would this be practically possible.

**Comment by DualCoder** [comment]
So in theory yes. It would be possible to apply the patches without DKMS. You would have to find a way to patch the source code before it gets built by the installer. Currently we let it build, remove it using DKMS, edit the source code, and rebuild/reinstall using DKMS.

If this answers your question, then please close this issue.

**Comment by moriel5** [comment]
Thanks, is does answer the question.
Closing the issue now.
