### ISSUE TITLE
Would this work with a Quadro p2000 card?

### ISSUE THREAD

**Issue by wmantly** [DualCoder/vgpu_unlock#32]
Hello all,

I have a Quadro p2000 card in a Promxox box and would love to get some vGPU's out of it since all it currently does is transcode for emby. Would this "unlock" work for this card? Would it work with Proxmox?

**Comment by KrutavShah** [comment]
Yes, we have P2000 in the list, so this should work out just fine, with Proxmox. You can join the discord server if you need help setting it up. Thanks.

**Comment by wmantly** [comment]
Thank you, im going to migrate the loads on that box and give it a shot.
