### ISSUE TITLE
Is it possible to unlock on a windows Hyper-V host?

### ISSUE THREAD

**Issue by scyto** [DualCoder/vgpu_unlock#35]
I am hoping there might be some way to unlock this for use with Hyper-V.

Is that possible using something like WSL or do I need to unlock on linux host and then transfer card to my hyper-v host?

**Comment by DualCoder** [comment]
No, this simply will not work for Hyper-V. It is linux only, and essentially none of the code has a Windows/Hyper-V equivalent.

**Comment by soroshsabz** [comment]
I think it is very useful to port this hack on windows
