### ISSUE TITLE
how hook rtx2070 super to tesla t4?,I can't find nvidia-installer,only for xxx.rmp

### ISSUE THREAD

**Issue by 20170819** [DualCoder/vgpu_unlock#39]
hello,I want to  hook rtx2070 super to tesla t4,but My GPU manager is NVIDIA-vGPU-rhel-7.6-440.53.x86_64.rpm.I can't find nvidia-installer? what is nvidia-installer ? Is it a shell run packet? what should I  do ? thanks you!

**Comment by KrutavShah** [comment]
You need to use the Linux KVM package of the vGPU drivers, and install it with DKMS. The RHEL driver doesn't have a DKMS option and therefore will not work. Please download the correct drivers at the license portal.

**Comment by 20170819** [comment]
thanks!
