### ISSUE TITLE
DKMS will not build for the latest vGPU drivers (460.32.04)

### ISSUE THREAD

**Issue by KrutavShah** [DualCoder/vgpu_unlock#4]
**While DKMS will build for driver 450, it will not with the newer versions. Here is the error:**

`[root@rhel-test vgpu]# dkms install -m nvidia -v 460.32.04

Creating symlink /var/lib/dkms/nvidia/460.32.04/source ->
                 /usr/src/nvidia-460.32.04

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=4.18.0-240.10.1.el8_3.x86_64 IGNORE_CC_MISMATCH='' modules...........(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.18.0-240.10.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/nvidia/460.32.04/build/make.log for more information.`

**Comment by DualCoder** [comment]
Please provide the content of `/var/lib/dkms/nvidia/460.32.04/build/make.log`.

**Comment by KrutavShah** [comment]
[https://pastebin.com/HphyyFYL](url)

The problem is only present with any drivers above 450, such as 460. 
This is an issue because the Nvidia vGPU customer portal only hosts the latest drivers, so you can no longer download 450 from there.

**Comment by DualCoder** [comment]
```
/bin/sh: 1: cannot open path_to_vgpu_unlock: No such file
```
Did you paste the lines without replacing the path? The first sentence of the `Installation` section in the readme states:
> In the following instructions `<path_to_vgpu_unlock>` need to be replaced with the path to this repository on the target system and `<version>` need to be replaced with the version of the NVIDIA GRID vGPU driver.

**Comment by KrutavShah** [comment]
Well I did exactly as you said and all correct paths were used. If you'd like, I can try again for 460. 450 driver builds just fine. Also, if you need the 460.32.04 driver package for testing, I can send that to you.

**Comment by DualCoder** [comment]
That is weird. If you don't mind I'd like you to double-check the path in `nvidia.Kbuild`. And if it is indeed correct, please do a search for the string `path_to_vgpu_unlock` in the `/var/lib/dkms/nvidia/460.32.04/build/` directory:
```
grep path_to_vgpu_unlock -r /var/lib/dkms/nvidia/460.32.04/build/
```

**Comment by KrutavShah** [comment]
I have double-checked the paths several times and have got the DKMS to install successfully. However this time it appears that the vgpu_unlock is incompatible with 460 drivers as the `mdev_supported_types` folder never gets created.

**Comment by DualCoder** [comment]
> I have double-checked the paths several times and have got the DKMS to install successfully. However this time it appears that the vgpu_unlock is incompatible with 460 drivers as the `mdev_supported_types` folder never gets created.

Ok, looks like I will have to make some tests with the 460 version. Let's hope it's not too difficult to support multiple versions.

**Comment by arki05** [comment]
In my testing 460.32.04 worked fine (tested on Proxmox 6.3.6).

**Comment by KrutavShah** [comment]
Can you explain how you got it working? The driver builds fine on the same Proxmox version but the VFIO hooks script is unable to grant vGPU. Only works on 450.89 for me.

**Comment by arki05** [comment]
After I solved the issues with the pci address range it worked straight away. Maybe you could enable logging, and then rebuild the module and afterwards post your logs ( dmesg or something ). 

Logging is enabled by changing a 0 to a 1 in vgpu_unlock_hook.c:
```
/* Debug logs can be enabled here. */
#if 0
	#define LOG(...) printk(__VA_ARGS__)
#else
	#define LOG(...)
#endif
```

Maybe then we can find a solution.

**Comment by KrutavShah** [comment]
Closing, seems to function, albeit some users are pointing out issues.
