### ISSUE TITLE
can't find nvidia file after successful install 460.32.04 linux kvm driver

### ISSUE THREAD

**Issue by IgerAnes** [DualCoder/vgpu_unlock#40]
hello everyone,
I follow the tutorial from [vGPU wiki](https://docs.google.com/document/d/1pzrWJ9h-zANCtyqRgS7Vzla0Y8Ea2-5z2HEi4X75d2Q/edit)  to set up the ubuntu 20.04  system. It works well, until to step 8 to modify four nvidia file.
I can't find any file named nvidia inside /lib/systemd/system/, I am not sure why there's no file inside.
I also remove nvidia driver and reinstall it again, everytime it said driver install sucessfully, but it still can't be found.
anyone can help me.

host system: ubuntu 20.04
cpu: amd 3600xt
gpu: 2060 super
driver: nvidia-linux-x86_64-460.32.04-vgpu-kvm.run (from nvidia licensing software download)(use --dkms install)
iommu: enable
svm: enable
grub_cmdline_linux_default: amd_iommu=on iommu=pt

**Comment by IgerAnes** [comment]
and after finish install nvidia driver,
my lightdm can't work, and the message show as below
`[FAILED] Failed to strat Detect the available GPUs and deal with any system changes`
`[FAILED] Failed to start Light Display Manager`
I use `systemctl status gpu-manager.service` to check my gpu status,
and it show message as below,
`gpu-manager.service: Start request repeated too quickly`
`gpu-manager.service: Failed with result 'start-limit-hit'`
anyone meet the same issue.

**Comment by sigboe** [comment]
Yes, the nvidia-linux-x86_64-460.32.04-vgpu-kvm.run does not have "DRM" or Direct Rendering Manager or whatever needed to run graphical programs including X or Wayland on the driver. The vgpu-kvm driver is meant for headless use. That is without a monitor attached.

Luckily for us, someone has managed to litterally merge 460.32.04-vgpu-kvm with the retail version of 460.32.03 (often called gforce driver in the community). Go to discord to learn how to install the merged driver.

**Comment by IgerAnes** [comment]
@sigboe thank you. I'll try it. :)

**Comment by IgerAnes** [comment]
umm.. I tried to use the merged-vgpu-driver to install.
run `./nvidia-installer --dkms`
happily, the lightdm can work will, but I still can't find nvidia file at /lib/systemd/system/ @@.
I used `find *.service | grep nvidia` to search nvidia-vgpud.service, no result appear.
`imilab@imilab-test:/lib/systemd/system$ find *.service | grep nvidia
imilab@imilab-test:/lib/systemd/system$ nvidia-smi`
I also use `nvidia-smi ` to test if I install driver correctly, it actually appear the result.
`Thu Apr 22 13:44:22 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 206...  Off  | 00000000:07:00.0 Off |                  N/A |
|  0%   53C    P8    23W / 184W |    180MiB /  8183MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     15080      G   /usr/lib/xorg/Xorg                 86MiB |
|    0   N/A  N/A     15219      G   /usr/bin/gnome-shell               30MiB |
|    0   N/A  N/A     16705      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A     17021      G   /usr/lib/firefox/firefox            1MiB |
+-----------------------------------------------------------------------------+
`

**Comment by IgerAnes** [comment]
Thanks everyone on discord
I found out that my ubuntu install nvidia driver to the wrong directory, after using `sudo systemctl cat nvidia-vgpud`.
![Screenshot from 2021-04-22 14-51-31](https://user-images.githubusercontent.com/32257146/115670549-1d6eb980-a37c-11eb-807c-c3b0e75de4de.png)
If you have same issue, hope will help someone. :)
