### ISSUE TITLE
hello,after vgpu_unlock is ok,license is still need for render video? 

### ISSUE THREAD

**Issue by 20170819** [DualCoder/vgpu_unlock#44]
hello,after vgpu_unlock is operated succefully,  nvidia license is still need for render video。 how to unlock nvidia license ? Is there any plan for unlock nvidia license? thank you !

**Comment by ALLINNNN** [comment]
Hello, I am trying to deploy vgpu_unlock, but I do not know which hypervisor should to be used, Vmware sPhere or XenServer? When I try to deploy vgpu_unlock on Vmware sPhere, some instructions do not exits on this platform, such as systemctl...
Could you please give me some advise? Thanks a lot in advance :)

**Comment by 20170819** [comment]
> Hello, I am trying to deploy vgpu_unlock, but I do not know which hypervisor should to be used, Vmware sPhere or XenServer? When I try to deploy vgpu_unlock on Vmware sPhere, some instructions do not exits on this platform, such as systemctl...
> Could you please give me some advise? Thanks a lot in advance :)
------no ,please new a topic for you question。as I known,this proj only support kvm hypervisor.my practice is kvm+qemu。

**Comment by KrutavShah** [comment]
Only Linux KVM is supported. We recommend Red Hat Enterprise Linux, for example. VMWare and Xenserver are not supported by this project. You still need a license to gain the full functionality of a vGPU, as this tool is NOT designed to bypass licenseing.

**Comment by ALLINNNN** [comment]
> Hello, I am trying to deploy vgpu_unlock, but I do not know which hypervisor should to be used, Vmware sPhere or XenServer? When I try to deploy vgpu_unlock on Vmware sPhere, some instructions do not exits on this platform, such as systemctl...
> Could you please give me some advise? Thanks a lot in advance :)
> ------no ,please new a topic for you question。as I known,this proj only support kvm hypervisor.my practice is kvm+qemu。

I see. I am sorry about that. THANKS!

**Comment by ALLINNNN** [comment]
> Only Linux KVM is supported. We recommend Red Hat Enterprise Linux, for example. VMWare and Xenserver are not supported by this project. You still need a license to gain the full functionality of a vGPU, as this tool is NOT designed to bypass licenseing.

OK, THANKS!
