### ISSUE TITLE
Built-in VNC and black screen

### ISSUE THREAD

**Issue by yatakoi** [DualCoder/vgpu_unlock#46]
Hi.

OS: CentOS 8.3 + KVM

If I create a guest (Windows 10 Pro), then by default I can connect to him via VNC. But as soon as I add vGPU

```
<hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci'>
  <source>
    <address uuid='30820a6f-b1a5-4503-91ca-0c10ba58692a'/>
  </source>
</hostdev>
```

, then when I connect through VNC, I see only a black screen.

Why is this happening?

![screen](https://user-images.githubusercontent.com/5018115/116849338-e6c55880-ac31-11eb-810e-945fa0922cf1.JPG)

**Comment by KrutavShah** [comment]
Nvidia vGPU documentation has some details on enabling the built-in VNC server. 

Intel GVT-G uses MDEVs as well, and there is some documentation on getting the display output of the MDEV on the internal QEMU display, whether you chose VNC or SPICE.

**Comment by DualCoder** [comment]
I have not tested this myself, but maybe this will help:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-device-GPU#sect-device-GPU-vGPU-VNC-console

It is for RHEL, but I think it should be relevant for CentOS as well.

**Comment by DualCoder** [comment]
Also, you will have to have the NVIDIA grid drivers installed in the guest before the VNC console will work.

**Comment by DualCoder** [comment]
I'm closing this since the question was answered.
