### ISSUE TITLE
iommu_group: No such file or directory (solved)

### ISSUE THREAD

**Issue by chinmoyrp** [DualCoder/vgpu_unlock#47]
For those who encounter this error while using _virt-manager_ or _qemu-system-*_. 
Ensure that the kernel modules `vfio_mdev` and `vfio_iommu_type1` are loaded. In my system (openSUSE Leap 15.2) they weren't and after a `modprobe` this issue was gone.

**Comment by KrutavShah** [comment]
Congratulations on solving your issue, please do close it now, thanks!
