### ISSUE TITLE
Lower tier SKUs for vGPU not advisable

### ISSUE THREAD

**Issue by KrutavShah** [DualCoder/vgpu_unlock#5]
I noticed that cards like the 1060 3GB are included in the list of GPUs that can be marked as "vGPU capable" which is probably not the best idea. I say this because if a user tries to launch a profile that uses the entire video memory or multiple profiles on the same card without adequate memory available for both to remain stable when under load, the GPU host driver may fail and make the card inaccessible until reboot, or crash the system outright.

I don't know if it is possible to prevent the user from doing this within the vgpu_unlock_hooks.c file, but it may be possible to prevent all the profiles from being loaded at boot if they exceed the memory available. For example, prevent loading of P4-8Q on 1060 3GB.

It's a rather minor issue, and the host driver may have protection capability. But if it doesn't this can become an issue on certain cards.

**Comment by DualCoder** [comment]
I agree. This is not advisable, however, if a user really wants to then I don't see why the tools shouldn't allow it.

It would be possible to limit the types of profiles within the `vgpu_unlock_hooks.c` file, but not the count. For example it is possible to prevent the loading of the P4-8Q profile on the 1060 3GB, but it is not possible to prevent loading four instances of the P4-1Q profile.

I would assume that something in the driver would detect the insufficient amount of RAM and prevent the loading of these configurations anyway. But I have not tested this.

I had the idea of getting rid of the PCI ID spoofing altogether and just provide our own profiles for these GPUs. For example we could have a GTX1060-1Q profile, and only allow three instances of it on the 3GB 1060. But this would definitely require more knowledge before it can be implemented.

**Comment by KrutavShah** [comment]
> I had the idea of getting rid of the PCI ID spoofing altogether and just provide our own profiles for these GPUs. For example we could have a GTX1060-1Q profile, and only allow three instances of it on the 3GB 1060. But this would definitely require more knowledge before it can be implemented.

I had the same idea as well, and here's how to do it. In /usr/share/nvida, there is a file called`vgpuConfig.xml`. This is where all the profiles live. Each profile has certain values, such as licensing required, max resolution, max vRAM, and so on. Each one of these profiles are backed by a signature, kind of like the signatures that have to be worked around by the vgpu_unlock_hooks.c to actually make the magic possible. I don't know much about these signatures, but I'm assuming that somewhere in the driver is a code that checks for signatures on each of these profiles.

Assuming that the driver is smart enough to know that the vGPU profile has crossed the limit, it shouldn't be too big of an issue for now.

**Comment by KrutavShah** [comment]
Closing, seems like it doesn't matter anymore. Users are running into blue screens but that's on them for using profiles with more vRAM than their card has.
