### ISSUE TITLE
vgpu_unlock supports rtx3080

### ISSUE THREAD

**Issue by hw0505** [DualCoder/vgpu_unlock#50]
Does vgpu_unlock currently support rtx3080？If vgpu_unlock supports rtx3080, what type of vgpu is generated by rtx3080 and what version of the driver is used in the virtual machine.

**Comment by qfreiman** [comment]
look at the readme before creating an issue.

it says "Ampere support is currently a work in progress" so no it is not supported

**Comment by hw0505** [comment]
thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月12日(星期三) 上午10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DualCoder/vgpu_unlock] vgpu_unlock supports rtx3080 (#50)





 
look at the readme before creating an issue.
 
it says "Ampere support is currently a work in progress" so no it is not supported
