### ISSUE TITLE
ERROR: Unable to load the 'nvidia-vgpu-vfio' kernel module.

### ISSUE THREAD

**Issue by jbmorgado** [DualCoder/vgpu_unlock#53]
When trying to install the VGPU package and choosing DKMS, it complains it can't find the 'nvidia-vgpu-vfio' kernel module.

**Comment by jbmorgado** [comment]
This was due to vfio binding on bootup on Proxmox. Nothing to do with vgpu_unlock

**Comment by Fight-Monarch** [comment]
Hi, How do you solve the problem?
