### ISSUE TITLE
Clarification for use of x-pci mentioned in the Google Docs Wiki

### ISSUE THREAD

**Issue by thatsysadmin** [DualCoder/vgpu_unlock#64]
In the OpenGL instabilities section of the Google Doc Wiki that was written by @KrutavShah, it says:

“The other solution is to “spoof” the vGPU to a normal Quadro, such as a Quadro P4000 for example with the x-pci arguments for the mediated vGPU device in the virtual machine configuration. “

Is there an example of a VM .xml file anyone can share to help me configure this?
Thanks!

**Comment by Dardrai** [comment]
Yes and no - it depends on os/packages used. But xml does sound like libvirt and for that there is a guide in the discord server 

For Libvirt you can use my guide: https://discord.com/channels/829786927829745685/830520513834516530/872802747727106119

But in short:

> as dec
> ```
>     <qemu:arg value="-set"/>
>     <qemu:arg value="device.hostdev0.x-pci-device-id=6960"/>
> ```
> 
> or as hex
> ```
>     <qemu:arg value="-set"/>
>     <qemu:arg value="device.hostdev0.x-pci-device-id=0x1b30"/>
> ```
> 
> Fallowing are key requirements to work:
> 1. Clean Windows - safe mode and ddu uninstaller clean is enough
>    a) make snapshot before or clean up (DDU) after every try for best results!
> 2. Install/Try install the Quadro drivers download from NV page
> IMPORTANT: Driver version does matter and you may have to try out some different drivers out before you have success! 
> Or look in successful-setups if a poster has your GPU and look what he did - maybe you'll find the right driver version there and know also the right device to spoof to.
> 

> Driver (host): NVIDIA-Linux-x86_64-460.73.02-vgpu-kvm.run -> Merged-driver Pre-unlocked from Wiki Guide
> Guest: Windows 10 Pro 21H1
> Driver (vGPU guests): Spoofed Quadro P6000 - 462.59-quadro-rtx-desktop-notebook-win10-64bit-international-whql
