### ISSUE TITLE
GTX 1070 with Proxmox 6.4

### ISSUE THREAD

**Issue by bazzou789** [DualCoder/vgpu_unlock#65]
Hi,

I followed [this tutorial](https://docs.google.com/document/d/1bK7c1LmumoqM2C4Ed3p2xyo2nfFh-BCtmr5TPks-s8I/edit) from [Craft Computing video](https://www.youtube.com/watch?v=cPrOoeMxzu0).

I managed to install the Nvidia driver, but I can't get the log line that says that the script is working (vGPU unlock patch applied.) and I don't know why.

I have 2x Intel Xeon E5-2450 v2 with all the virtualization settings enabled in the BIOS and the GTX 1070 is detected and working since my monitor is plugged to it and is working fine.

I also edited the 4 files as mentioned in the wiki.

Is there a way to debug it or to get more info on why the script is not launched at boot ?

**Comment by V13Axel** [comment]
So, chances are you actually have it installed and working correctly. 

The debug logging is disabled by default, you'll need to change this 0 to a 1 if you want to verify the dmesg output:

https://github.com/DualCoder/vgpu_unlock/blob/f432ffc8b7ed245df8858e9b38000d3b8f0352f4/vgpu_unlock_hooks.c#L567-L571

**Comment by crash987** [comment]
i to am also having the same problem. i have changed the vgpu_unlock_hooks.c file like what you have said, aswell as removing the "#" from each line still having the same problem, no line saying "vgpu unlock patch applied". I have tried both nevidia driver 450.80 and also 460.32.08. Any help would be great

**Comment by bazzou789** [comment]
@V13Axel thanks for the help. With this change, I was able to see that it was working well in the dmesg output.

@crash987 I don't know if it's related, but there seems to be a glitch when you clone the project directly from Git. I was recommended to download the project from Git as a zip file and then copy it to the server by SCP.
