### ISSUE TITLE
Windows BSOD (GeForce 3080)

### ISSUE THREAD

**Issue by AlexNg11** [DualCoder/vgpu_unlock#67]
I enabled vgpu_unlock on a geforce 3080, setup one Windows 10 VM, installed GRID driver 460.32.04. It seems Windows does see one NVIDIA A6000-4Q instance, but after reboot Windows, it always BSOD. Any idea? Thx.

**Comment by gardotd426** [comment]
Why was this issue closed? Was the issue fixed, or??? The wiki says Ampere isn't supported, so I'm curious to know whether you actually got it working.

**Comment by jrstarke** [comment]
I’m guessing this is closed because ampere is currently unsupported: https://github.com/DualCoder/vgpu_unlock/issues/8#issuecomment-817062916
