### ISSUE TITLE
Rtx A5000

### ISSUE THREAD

**Issue by ssdeol84** [DualCoder/vgpu_unlock#76]
Can we unlock RTX A5000 on VMware or proxmox ?

**Comment by DualCoder** [comment]
According to https://docs.nvidia.com/grid/gpus-supported-by-vgpu.html the RTX A5000 is natively supported, so no unlocking is required. I.e it should work without vgpu\_unlock.

**Comment by ssdeol84** [comment]
Means we can use vGPU without buying license from nvidia in VMware for sharing GPU

**Comment by DualCoder** [comment]
vgpu\_unlock enables the use of vGPU on additional graphics cards that are not natively supported (like geforce and lower tier quadro), but you still need a valid license to obtain and run the vGPU software. If you try to circumvent the licensing then you are probably committing copyright infringement, which neither I nor vgpu\_unlock will help you with.
