### ISSUE TITLE
Way to use vGPU without license

### ISSUE THREAD

**Issue by ssdeol84** [DualCoder/vgpu_unlock#77]
Sir is there any way to use vGPU without any license..I want to use it for study project
 So I don't have budget to buy license

Is there any free way to use vGPU

**Comment by DualCoder** [comment]
The only free option that I am aware of is to register for a 90-day trial (https://enterpriseproductregistration.nvidia.com/?LicType=EVAL&ProductFamily=vGPU), but then you need to finish your project within the 90-day window.

If this is for an education project then you might qualify for the "NVIDIA Education Pricing Program" which I assume would offer you a discount on licenses.

Either way, if you have questions about available licensing options then I suggest you contact NVIDIA or one of their partners directly.
