### ISSUE TITLE
Is it required to use merge driver for following settings?

### ISSUE THREAD

**Issue by mcdull** [DualCoder/vgpu_unlock#78]
AMD 3900x = X470
1 x nVidia 1080 (complete passthrough)
1 x nVidia 1050 Ti (vgpu unlock)

I found it always complains the group has been used. 
As I have no other GPU for host display and I do not need it, I suspect host uses some of the resources and making it unavailable to the driver.  Is it possible to use the normal driver or I must use the merged driver for my setup?

I would like to avoid using merge driver if it is not mandatory. Thank you.

**Comment by mcdull** [comment]
For first boot, the VM boots fine, but display shutter and parsec can only last for a minute and very unresponsive.
The 2nd boot will result in the following error.

kvm: -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:0f:00.0/00000000-0000-0000-0000-000000000102,id=hostpci0,bus=ich9-pcie-port-1,addr=0x0: vfio 00000000-0000-0000-0000-000000000102: error getting device from group 24: Input/output error
Verify all devices in group 24 are bound to vfio-<bus> or pci-stub and not already in use

**Comment by mcdull** [comment]
Okay. initial testing shows that vgpu unlock is not compatible with new drivers...
460 versions works fine with same procedure.

**Comment by Dardrai** [comment]
If you run hostless, or have a third amd/intel gp, then no you don't need merged drivers - if you want to use vgpu on the 1050 and use this card for the host too, then you'll need merged drivers

**Comment by mcdull** [comment]
Thanks. I can confirm this.  Now I am running headless and everything is fine.  Just to remember to use the OLD driver.
