### ISSUE TITLE
rtx2060 12g vgpu opengl unavailable

### ISSUE THREAD

**Issue by wnark** [DualCoder/vgpu_unlock#98]
Since the 2060  12g must use the newer vGPU host driver on the host, 
use this :https://gitlab.com/polloloco/vgpu-proxmox

even if I use the original quadro driver in the guest, Windows is still stuck when running spec13

**Comment by wnark** [comment]
even if I use the original quadro driver in the guest, Windows is still stuck when running spec13
just like :p2000_450.80kvm_453.10-quadro-desktop-notebook-win10-64bit-international-whql.exe
or Original quadro driver：471.41-quadro-rtx-desktop-notebook-win10-64bit-international-dch-whql.exe

dmesg:
![1655610078068](https://user-images.githubusercontent.com/24355466/174464874-75854bb9-329e-4a86-a76c-c2d79b438bd1.png)

![image](https://user-images.githubusercontent.com/24355466/174464878-ea055277-5c9e-486a-9864-6dc065d0a8d9.png)

**Comment by shiwaimanong** [comment]
@wnark I tested GTX 1050, GTX 1050 Ti, GTX 1660, RTX 2060 12GB, they works fine with windows 10/11.

* VM Host System: Ubuntu 22.04 Desktop
* VM Host Driver: NVIDIA-Linux-x86_64-510.85.03-vgpu-kvm.run
* vgpu patcher: https://github.com/VGPU-Community-Drivers/vGPU-Unlock-patcher
* vgpu unlock: https://github.com/mbilker/vgpu_unlock-rs.git

`/etc/vgpu_unlock/profile_override.toml` :

```
[profile.nvidia-257]
num_displays = 1
display_width = 1920
display_height = 1080
max_pixels = 2073600
```

Windows 10/11 Gust GPU Driver: 496.49-quadro-rtx-desktop-notebook-win10-win11-64bit-international-dch-whql.exe

Notice: RTX 3060 or newer not support!

**Comment by wnark** [comment]
> @wnark I tested GTX 1050, GTX 1050 Ti, GTX 1660, RTX 2060 12GB, they works fine with windows 10/11.
> 
> * VM Host System: Ubuntu 22.04 Desktop
> * VM Host Driver: NVIDIA-Linux-x86_64-510.85.03-vgpu-kvm.run
> * vgpu patcher: https://github.com/VGPU-Community-Drivers/vGPU-Unlock-patcher
> * vgpu unlock: https://github.com/mbilker/vgpu_unlock-rs.git
> 
> `/etc/vgpu_unlock/profile_override.toml` :
> 
> ```
> [profile.nvidia-257]
> num_displays = 1
> display_width = 1920
> display_height = 1080
> max_pixels = 2073600
> ```
> 
> Windows 10/11 Gust GPU Driver: 496.49-quadro-rtx-desktop-notebook-win10-win11-64bit-international-dch-whql.exe
> 
> Notice: RTX 3060 or newer not support!

Hello, when I use spec13 to run the score, Windows crashes during the snx project. If the following options are not used, Windows will crash.
which is
```
[profile.nvidia-435]
vgpu_type = "NVS"
pci_id = 0x1e301437
pci_device_id = 0x1e30
```
However, I found that using the card_name parameter is invalid, and using GPU-Z can still display: GRID RTX6000-1B in: WDDM, opengl, and cuda, even if it has been replaced. This ID can be found in the registry

**Comment by wnark** [comment]
https://gitlab.com/polloloco/vgpu-proxmox

it works great
